### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by dprov** [YiLiM1/DANet#1]
Hi, 
First of all, very interesting work and ICRA presentation! I especially appreciate the PST as a means to 1) circumvent some of the issues of lightweight depth estimation models and 2) making it more realistic to leverage Transformers on embedded platforms.

With that being said, would you mind specifying under which licence the code is published (especially if you allow commercial research use)?
Thanks

**Comment by YiLiM1** [comment]
Publishe under GPL 3.0

**Comment by YiLiM1** [comment]
> Hi, First of all, very interesting work and ICRA presentation! I especially appreciate the PST as a means to 1) circumvent some of the issues of lightweight depth estimation models and 2) making it more realistic to leverage Transformers on embedded platforms.
> 
> With that being said, would you mind specifying under which licence the code is published (especially if you allow commercial research use)? Thanks

Publishe under GPL 3.0
